PV:pn-packagegroup-application-layer= "1.1.0"
PR:pn-packagegroup-application-layer= "r0"
PACKAGE_ARCH:pn-${MLPREFIX}packagegroup-application-layer = "${APPLICATION_LAYER_ARCH}"

PV:pn-rdkresidentapp= "1.0.0"
PR:pn-rdkresidentapp= "r0"
PACKAGE_ARCH:pn-${MLPREFIX}rdkresidentapp = "${APPLICATION_LAYER_ARCH}"

PV:pn-residentui= "1.0.0"
PR:pn-residentui= "r0"
PACKAGE_ARCH:pn-${MLPREFIX}residentui = "${APPLICATION_LAYER_ARCH}"

