PV_pn-packagegroup-application-layer= "1.0"
PR_pn-packagegroup-application-layer= "r0"
PACKAGE_ARCH_pn-lib32-packagegroup-application-layer = "${APPLICATION_LAYER_ARCH}"

PV_pn-rdkresidentapp= "1.0.0"
PR_pn-rdkresidentapp= "r0"
PACKAGE_ARCH_pn-lib32-rdkresidentapp = "${APPLICATION_LAYER_ARCH}"

PV_pn-residentui= "1.0.0"
PR_pn-residentui= "r0"
PACKAGE_ARCH_pn-lib32-residentui = "${APPLICATION_LAYER_ARCH}"

